### ISSUE TITLE
[📝 Task] Client : footer 디자인 수정

### ISSUE THREAD

**Issue by 2-phones** [codestates-seb/seb39_main_018#189]
## ISSUE
- Group : 'Client'
- Type : design
- Detail : footer 디자인 수정

## Todo
- [ ] 로딩 이벤트 구현
- [ ] 랜딩 페이지 마저 작업
- [x] footer 디자인 수정
