### ISSUE TITLE
[📝 Task] Server : 게시물 이미지 S3 업로드 기능 에러 잡고 완성

### ISSUE THREAD

**Issue by 2-phones** [codestates-seb/seb39_main_018#233]
## ISSUE
- Group : Server
- Type : feat
- Detail :  게시물 이미지 S3 업로드 기능 에러 잡고 완성
## Todo

- [ ] 게시물 CRUD 요청 모듈화
- [ ] 로그인 회원가입 cors 에러 잡고 토큰 처리 기능 완성
- [ ] S3 업로드 기능 완성하기
- [ ] 채팅 백엔드 연동
